config/routes.rb
AmblesidecommunityOrg::Application.routes.draw do
  get "comments/destroy"

  resources :comments, only: :destroy

  resources :documents, except: :show

  resources :events

  match '/posts/:id/add_comment', to: 'posts#add_comment'
  resources :posts
  match '/blog', :to => 'posts#index'
  match '/positions/ahoa', :controller => 'positions',
    :action => 'ahoa', :as => :ahoa
  resources :positions, :except => :show

  match '/residents/get_csv', :controller => 'residents',
    :action => 'get_csv', :as => :get_csv 
  resources :residents

  match '/users/:id/verify_email/:code', :to => 'users#verify_email',
    :as => :verify_email
  match '/users/:id/toggle_active', :to => 'users#toggle_active', 
    :as => :toggle_active
  match '/users/:id/edit_roles', :to => 'users#edit_roles',
    :as => :edit_roles
  match '/users/:id/update_roles', :to => 'users#update_roles'
  match 'positions/:id/edit_assignment', :to => 'positions#edit_assignment',
    :as => :edit_assignment
  match 'positions/:id/update_assignment', :to => 'positions#update_assignment'
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :password_resets

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/community', :to => 'pages#community'
  match '/dues', :to => 'pages#dues'
  
  root :to => 'pages#home'

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer         not null, primary key
#  email                  :string(255)
#  encrypted_password     :string(255)
#  salt                   :string(255)
#  resident_id            :integer
#  is_active              :boolean         default(FALSE)
#  created_at             :datetime
#  updated_at             :datetime
#  password_reset_token   :string(255)
#  password_reset_sent_at :datetime
#  sign_in                :datetime
#

require 'digest'
class User < ActiveRecord::Base
  attr_accessor :password
  attr_accessible :email, :password, :password_confirmation, :is_active, :resident_attributes
  belongs_to :resident, :validate => true, :dependent => :destroy
  has_many :assignments, :dependent => :destroy
  has_many :roles, :through => :assignments, :uniq => true
  has_one :position, :dependent => :nullify, :readonly => true
  has_many :posts
  has_many :documents
  has_many :comments
  validates_presence_of :resident

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, :presence => true,
                    :format => { :with => email_regex },
                    :uniqueness => { :case_sensitive => false },
                    :on => :create

  # Automatically creates the virtual attribute 'password_confirmation'.
  validates :password,  :presence      => true, :on => :create
  validates :password,  :confirmation  => true, :on => :create
  validates :password,  :length        => { :within => 6..40 }, :on => :create

  #validates :resident_id,   :presence  => true

  before_save :encrypt_password, :unless => Proc.new { |u| u.password.blank? }

  # Return true if the user's password matches the submitted password.
  def has_password?(submitted_password)
    encrypted_password == encrypt(submitted_password)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  def role_symbols
    (roles || []).map { |r| r.name.underscore.to_sym }
  end

  def is_admin?
    role_ids.include?(1)
  end

  def send_email_verification
    generate_token(:password_reset_token)
    save!
    UserMailer.email_verification(self).deliver
  end

  def send_password_reset
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
    UserMailer.password_reset(self).deliver
  end

  private
    def generate_token(column)
      begin
        self[column] = SecureRandom.urlsafe_base64
      end while User.exists?(column => self[column])
    end

    def encrypt_password
      self.salt = make_salt unless has_password?(password)
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper
  filter_resource_access
  before_filter :is_myself, :only => [:destroy, :toggle_active]
  before_filter :go_ssl, :only => [:new, :create, :edit, :update, :verify_email]
  layout :get_layout 
	
  def index
    @title = 'All users'
    @users = User.order("email asc")
  end

  def show
    @title = @user.email
  end

  def new
    @resident = @user.build_resident
    @residence = @resident.build_residence
    @title = "Sign up"
  end

  def create
    if User.count == 0
      @user.role_ids = [1]
      @user.is_active = true
    else
      @user.role_ids = [3]
    end
		
    @resident = @user.build_resident(params[:user][:resident])

    residence_values = params[:user][:resident][:residence]
    if !residence_values.nil?
      @residence = Residence.assign_residence(residence_values,
        @resident) 
    else
      @residence = @resident.build_residence
    end

    if @user.save
      if Preauth.find_by_email(@user.email)
          UserMailer.new_auto_user(@user).deliver
          @user.send_email_verification
          redirect_to root_url, notice: 'Welcome to Ambleside. Please check your email for verification.'
      else
        UserMailer.welcome_email(@user).deliver
        UserMailer.new_user(@user).deliver
        flash[:success] = 'Welcome to Ambleside! Your account is ' +
            'pending approval.'
        redirect_to new_session_path
      end
    else 
      @title = 'Sign up'
      @user.password.clear()
      @user.password_confirmation.clear()
      render 'new'
    end
  end

  def edit
    @resident = @user.resident
    @residence = @resident.residence
    @title = 'Edit user'
  end

  def edit_roles
    @title = 'Edit roles'
  end

  def update
    @resident = @user.resident
    @residence = Residence.assign_residence(
      params[:user][:resident][:residence], 
      @resident)

    resident_values = params[:user][:resident]
    resident_values[:residence_id] = @resident.residence_id
    resident_values[:residence] = @resident.residence.attributes

    if @user.update_attributes(params[:user]) & 
      @user.resident.update_attributes(resident_values)
      flash[:success] = "Profile updated."
      redirect_to @user
    else
      @user.password.clear()
      @user.password_confirmation.clear()
      @title = 'Edit user'
      render 'edit'
    end
  end

  def update_roles
    params[:role_ids] ||= []
    @user.role_ids = params[:role_ids] 
    flash[:success] = "Roles updated"
    redirect_to users_path
  end

  def toggle_active
    if @user.is_active?
      @user.update_attribute(:is_active, false)
    else
      @user.send_email_verification
    end
    redirect_to users_path
  end 

  def verify_email
    user = User.find_by_password_reset_token(params[:code])
    if user
      user.update_attribute(:is_active, true)
      user.update_attribute(:password_reset_token, nil)
      redirect_to new_session_path, notice: 'Your email has been verified. Please sign in.'
    else
      redirect_to root_url, notice: 'There was a problem verifying your email.'
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    flash[:success] = "User destroyed."
    redirect_to users_path
  end

  private
    def is_myself
      user = User.find(params[:id])
      if user.id == current_user.id
        flash[:error] = "You can't administer yourself"
        redirect_to users_path
      end
    end

    def correct_user
      user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(user) ||
        current_user.admin?
    end

    def not_signed_in
      redirect_to(root_path) unless !signed_in?
    end

    def get_layout
      if['new', 'create'].include? action_name
        'pages_minimal'
      else
        'application'
      end
    end

end

app/helpers/users_helper.rb
module UsersHelper
  def authenticate
    deny_access unless signed_in?
  end

  def admin_user
    redirect_to(root_path) unless current_user.admin?
  end
end

app/views/users/_fields.html.erb
<%= render 'shared/error_messages', :object => @user %>
<% if !@resident.user.nil? %>
  <div>
    <%= gravatar_for @user.resident, :size => 100 %>
    <a href="http://gravatar.com/emails" target="_blank">change</a>
  </div>
<% end %>
<div class="field">
  <%= f.label :email %><br />
  <%= f.text_field :email %>
</div>
<div class="field">
  <%= f.label :password %><br />
  <%= f.password_field :password %>
</div>
<div class="field">
  <%= f.label :password_confirmation %><br />
  <%= f.password_field :password_confirmation %><br />
</div>
<%= f.fields_for(@resident) do |rf| %>
  <%= render 'residents/fields', :f => rf %> 
<% end %>

app/views/users/_user.html.erb
<tr>
  <td>
    <%= link_to user.resident.last_name + ', ' + 
      user.resident.first_name, user %>
  </td>
  <td>
    <%= user.sign_in %>
  </td>
  <td>
    <% user.roles.each do |r| %>
      <%= "#{r.name} " %>
    <% end %>
  </td>
  <td>
    <% permitted_to? :toggle_active, user do %> 
      <% if user.assignments.empty? %>
        <%= link_to 'roles', edit_roles_path(user.id),
          style: "font-weight:bold;font-size:1.25em;color:Red;" %>
      <% else %>
        <%= link_to 'roles', edit_roles_path(user.id) %>
      <% end %>
      <% if !user.is_active? %>
        <% if user.password_reset_token %>
          <%= link_to 'activated', toggle_active_path(user.id),
            style: "color:Green;" %>
        <% else %>
          <%= link_to 'activate', toggle_active_path(user.id),
            style: "font-weight:bold;font-size:1.25em;color:Red;" %>
        <% end %>
      <% else %>
        <%= link_to 'deactivate', toggle_active_path(user.id),
          :confirm => "You sure?",
          :title => "#{user.email}"  %>
      <% end %>
      <% permitted_to? :destroy, user do %>
      <%= link_to 'edit', edit_user_path(user.id) %>
      <%= link_to 'delete', user, :method => :delete, :confirm => "You sure?",
                                  :title => "Delete #{user.email}" %>
      <% end %>
    <% end %>
  </td>
</tr>

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= form_for(@user) do |f| %>
  <%= render 'fields', :f => f %>
  <div class="actions">
    <%= f.submit 'Update' %>
  </div>
<% end %>

app/views/users/edit_roles.html.erb
<h1><%= @user.resident.first_name + ' ' + 
  @user.resident.last_name %></h1>

<%= form_tag '/users/' + @user.id.to_s + '/update_roles', :method => :post do -%>
  <% for r in Role.all %>
    <div>
      <%= check_box_tag "role_ids[]", r.id, @user.roles.include?(r) %>
      <%= r.name %>
    </div>
  <% end %>
  <br />
  <%= submit_tag 'Update roles' %>
<% end %>

app/views/users/index.html.erb
<h1>All users</h1>

<table class="users">
  <th>Name</th>
  <th>Last SignIn/Remembered</th>
  <th>Roles</th>
  <th>Actions</th>
  <%= render @users %>
</table>

app/views/users/new.html.erb
<% content_for :body do %>
  <div id="su-half"></div>
  <div id="signup">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/signin_title', :s => 'Sign Up' %>
      <div class="clearfix" id="signin-main">
        <%= render 'fields', :f => f %>
        <div class="clearfix" id="signin-actions">
          <div class="actions right">
            <%= f.submit "Sign up" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/users/show.html.erb
<ul class="plain-list">
  <li>
    <%= gravatar_for(@user.resident, { :size => 100 }) %>
  </li>
  <li>
    <h1>
      <%= @user.resident.first_name + ' ' +
        @user.resident.last_name %>
    </h1>
  </li>
  <% if !@user.position.nil? %>
    <li class="show-value">
      <%= 'AHOA ' + @user.position.name %>
    </li>
  <% end %>
  <li class="show-value">
    <%= mail_to @user.email, @user.email, :encode => 'hex' %>
  </li>
  <li class="show-value">
    <%= "(#{@user.resident.phone_area_code})
      #{@user.resident.phone_prefix}-#{@user.resident.phone_suffix}" %>
  </li>
  <li class="show-value">
    <%= @user.resident.residence.street_number.to_s + ' ' +
      @user.resident.residence.street_name %>
  </li>
  <li class="show-value">
    <%= link_to 'edit Me', edit_user_path(@user) %>
  </li>
</ul>