config/routes.rb
AmblesidecommunityOrg::Application.routes.draw do
  get "comments/destroy"

  resources :comments, only: :destroy

  resources :documents, except: :show

  resources :events

  match '/posts/:id/add_comment', to: 'posts#add_comment'
  resources :posts
  match '/blog', :to => 'posts#index'
  match '/positions/ahoa', :controller => 'positions',
    :action => 'ahoa', :as => :ahoa
  resources :positions, :except => :show

  match '/residents/get_csv', :controller => 'residents',
    :action => 'get_csv', :as => :get_csv 
  resources :residents

  match '/users/:id/verify_email/:code', :to => 'users#verify_email',
    :as => :verify_email
  match '/users/:id/toggle_active', :to => 'users#toggle_active', 
    :as => :toggle_active
  match '/users/:id/edit_roles', :to => 'users#edit_roles',
    :as => :edit_roles
  match '/users/:id/update_roles', :to => 'users#update_roles'
  match 'positions/:id/edit_assignment', :to => 'positions#edit_assignment',
    :as => :edit_assignment
  match 'positions/:id/update_assignment', :to => 'positions#update_assignment'
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :password_resets

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/community', :to => 'pages#community'
  match '/dues', :to => 'pages#dues'
  
  root :to => 'pages#home'

end

app/views/shared/_action_bar.html.erb
<% if permitted_to? :create, target %>
  <div class="action-bar clearfix">
    <div class="action-button">
      <%= link_to link_title, link_path %>
    </div>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(object.errors.count, 'error') %>
    prohibited this <%= object.class.to_s.underscore.humanize.downcase %>
    from being saved:</h2>
  <p>There were problems with the following fields:</p>
  <ul>
    <% object.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_navigation.html.erb
<nav>
  <ul class="clearfix">
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'About', about_path %></li>
    <li><%= link_to 'Contact', contact_path %></li>
    <% if permitted_to? :index, :residents %>
      <li class="drop-down-root"><%= link_to 'Community', community_path %>
        <ul class="profile-drop-down">
          <li><%= link_to 'Residents', residents_path %></li>
          <li><%= link_to 'Blog', blog_path %></li>
          <li><%= link_to 'Events', events_path %></li>
        </ul>
      </li>
      <% permitted_to? :ahoa, :positions do %>
        <li class="drop-down-root"><%= link_to 'AHOA', ahoa_path %>
          <ul class="profile-drop-down">
            <% permitted_to? :destroy, :positions do %>
              <li><%= link_to 'Positions', positions_path %></li>
            <% end %>
            <li><%= link_to 'Documents', documents_path %></li>
            <li><%= link_to 'Dues', dues_path %></li>
          </ul>
        </li>
      <li class="drop-down-root"><%= link_to 'Me', current_user %>
        <ul class="nav-last profile-drop-down">
          <li><%= link_to 'Settings', edit_user_path(current_user) %></li>
          <li><%= link_to 'Sign out', signout_path, :method => :delete %></li>
        </ul>
      </li>
      <% end %>
      <% permitted_to? :toggle_active, :users do %>
        <li class="drop-down-root">Admin
          <ul class="nav-last profile-drop-down">
            <li><%= link_to 'Users', users_path %></li>
          </ul>
        </li>
      <% end %>
    <% else %>
    <li><%= link_to 'Sign in', signin_path %></li>
    <% end %>
  </ul>
</nav>

app/views/shared/_signin_title.html.erb
<div class="clearfix" id="signin-title">
  <div style="float:left;">
    <%= s %>  
  </div>
  <div id="small-nav">
    <%= link_to 'Home', root_path %> /  
    <%= link_to 'About', about_path %>
  </div>
</div>

app/views/shared/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<%= stylesheet_link_tag 'base', :media => 'screen' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= yield :style %>