config/routes.rb
AmblesidecommunityOrg::Application.routes.draw do
  get "comments/destroy"

  resources :comments, only: :destroy

  resources :documents, except: :show

  resources :events

  match '/posts/:id/add_comment', to: 'posts#add_comment'
  resources :posts
  match '/blog', :to => 'posts#index'
  match '/positions/ahoa', :controller => 'positions',
    :action => 'ahoa', :as => :ahoa
  resources :positions, :except => :show

  match '/residents/get_csv', :controller => 'residents',
    :action => 'get_csv', :as => :get_csv 
  resources :residents

  match '/users/:id/verify_email/:code', :to => 'users#verify_email',
    :as => :verify_email
  match '/users/:id/toggle_active', :to => 'users#toggle_active', 
    :as => :toggle_active
  match '/users/:id/edit_roles', :to => 'users#edit_roles',
    :as => :edit_roles
  match '/users/:id/update_roles', :to => 'users#update_roles'
  match 'positions/:id/edit_assignment', :to => 'positions#edit_assignment',
    :as => :edit_assignment
  match 'positions/:id/update_assignment', :to => 'positions#update_assignment'
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :password_resets

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/community', :to => 'pages#community'
  match '/dues', :to => 'pages#dues'
  
  root :to => 'pages#home'

end

app/models/resident.rb
# == Schema Information
#
# Table name: residents
#
#  id              :integer         not null, primary key
#  residence_id    :integer
#  last_name       :string(255)
#  first_name      :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#  phone_area_code :integer(3)
#  phone_prefix    :integer(3)
#  phone_suffix    :string(4)
#

class Resident < ActiveRecord::Base
  attr_accessible :last_name, :first_name,
    :residence_attributes, :phone_area_code, :phone_prefix, :phone_suffix
  has_one :user, :dependent => :destroy
  belongs_to :residence, :validate => true
  validates_presence_of :residence

  validates :last_name, :first_name, :phone_area_code, :phone_prefix,
    :phone_suffix, :presence => true

  validates :last_name, :first_name, :length => { :within => 1..15 }

  validates :phone_area_code, :phone_prefix,
    :numericality => { :only_integer => true }

  validates :phone_area_code, :phone_prefix, :length  => { :is => 3 }
  validates :phone_suffix, :length => { :is => 4 }

  validates_each :phone_suffix do |record, attr, value|
    record.errors.add(attr, 'must be a number') if value.to_i == 0
  end

  before_save do |user|
    user.last_name = user.last_name.capitalize
    user.first_name = user.first_name.capitalize
  end

end

app/controllers/residents_controller.rb
require 'csv'

class ResidentsController < ApplicationController
  include UsersHelper
  before_filter :new_resident_from_params, only: :create
  before_filter :new_resident, only: [:index, :new, :get_csv]
  before_filter :resident_from_id, only: [:edit, :show]
  filter_access_to :all, attribute_check: true
  before_filter :set_selected
  layout 'community'

  def index
    @title = 'All residents'

    @residents = all_residents 
  end

  def get_csv
    @residents = all_residents
    csv_string = CSV.generate do |csv|
      csv << ["Lot#", "Last Name", "First Name", "Email", "Street", "Phone"]

      last_lot = String.new
      @residents.each do |r|
        lot_number = r.residence.lot_number != last_lot ?
          r.residence.lot_number : ''

        csv << [lot_number, r.first_name, r.last_name,
          !r.user.nil? ? r.user.email : '', 
          "#{r.residence.street_number.to_s} #{r.residence.street_name}",
          "(#{r.phone_area_code}) #{r.phone_prefix}-#{r.phone_suffix}"]

          last_lot = r.residence.lot_number
      end
    end

    send_data csv_string, type: 'text/csv; charset=iso-8859-1; header-present',
      disposition: 'attachment; filename=residents.csv'
  end

  def show
    @title = @resident.last_name + ', ' + @resident.first_name
  end

  def new
    @residence = @resident.build_residence
    @title = 'New resident'
  end

  def create
    residence_values = params[:resident][:residence]
    if !residence_values.nil?
      @residence = Residence.assign_residence(residence_values,
        @resident)
    else
      @residence = @resident.build_residence
    end

    resident = params[:resident]
    if @resident.save
      flash[:success] = 'Resident was created successfully'
      redirect_to @resident 
    else
      render 'new'
    end
  end

  def edit
    @residence = @resident.residence
    @title = 'Edit resident'
  end

  def update
    @residence = Residence.assign_residence(
      params[:resident][:residence], @resident)
    
    resident_values = params[:resident]
    resident_values[:residence_id] = @resident.residence_id
    resident_values[:residence] = @resident.residence.attributes  
     
    if @resident.update_attributes(resident_values)
      flash[:success] = "Profile updated."
      redirect_to @resident
    else
      render 'edit'
    end
  end

  def destroy
    resident = Resident.find(params[:id])
		if resident.user.nil? || 
            (resident.user.id != current_user.id)
			resident.destroy
			flash[:success] = "Resident destroyed."
		else
			flash[:error] = "You can't administer yourself."
		end
    redirect_to residents_path
  end

  protected
  def new_resident_from_params
    @resident = Resident.new(params[:resident])
  end

  def new_resident
    @resident = Resident.new
  end

  def resident_from_id
    @resident = Resident.find(params[:id])
  end

  private
    def set_selected
      @selected = 'Residents'
    end

    def all_residents
       Resident.find_by_sql([
      "select residents.*, residences.lot_number
      from residents
      left outer join users
      on residents.id = users.resident_id
      inner join residences
      on residents.residence_id = residences.id
      where users.resident_id is null
      union select residents.*, residences.lot_number
      from residents
      inner join users on residents.id = users.resident_id
      inner join residences
      on residents.residence_id = residences.id
      where users.is_active = ? 
      order by lot_number asc, last_name asc, first_name asc", true])
    end
end

app/helpers/residents_helper.rb
module ResidentsHelper
  def gravatar_for(resident, options = { :size => 50 })
    gravatar_image_tag(resident.user.email.downcase, :alt => h(resident.user.email),
                                            :class => 'gravatar',
                                            :gravatar => options)
  end
end

app/views/residents/_fields.html.erb
<%= render 'shared/error_messages', :object => @resident %>
<div class="field">
  <%= f.label :last_name %><br />
  <%= f.text_field :last_name %><br />
</div>
<div class="field">
  <%= f.label :first_name %><br />
  <%= f.text_field :first_name %><br />
</div>
<div class="clearfix">
  <div><%= label_tag 'Phone' %></div>
  <div class="field float-left" id="area_code">
    <%= f.text_field :phone_area_code, :size => 3, :maxlength => 3 %><br />
  </div>
  <div class="field float-left" id="prefix">
    <%= f.text_field :phone_prefix, :size => 3, :maxlength => 3 %><br />
  </div>
  <div class="field float-left" id="suffix">
    <%= f.text_field :phone_suffix, :size => 4, :maxlength => 4 %><br />
  </div>
</div>
<%= f.fields_for(@residence) do |rf| %>
  <%= render 'residences/fields', :f => rf %>
<% end %>

app/views/residents/_resident.html.erb
<% info = { :good => false, :email => '' }
   if !resident.user.nil?
     info[:good] = true
     info[:email] = resident.user.email
   end
%>
<tr>
  <td><%= resident.residence.lot_number %></td>
  <td> 
    <%= link_to resident.last_name + ', ' +
      resident.first_name, resident %>
  </td>
  <td>
    <% if info[:good] %>
      <%= mail_to info[:email], info[:email], :encode => 'hex' %>
    <% end %>
  </td>
  <td>
    <%= resident.residence.street_number.to_s + ' ' + 
      resident.residence.street_name  %>
  </td>
  <td>
    <%= "(#{resident.phone_area_code})
      #{resident.phone_prefix}-#{resident.phone_suffix}" %>
  </td>
    <td class="right-align">
    <% permitted_to? :destroy, resident do %>
      <%= link_to 'edit', edit_resident_path(resident) %>
      <%= link_to 'delete', resident, :method => :delete, :confirm => 'You sure?',
                                      :title => "Delete #{resident.first_name +
                                      ' ' + resident.last_name}" %>
    <% end %>
  </td>
</li>

app/views/residents/edit.html.erb
<h1>Edit resident</h1>

<%= form_for(@resident) do |f| %>
  <%= render 'fields', :f => f %>
  <div class="actions">
    <%= f.submit 'Update' %>
  </div>
<% end %>

app/views/residents/index.html.erb
<div class="action-bar clearfix">
  <% if permitted_to? :create, :residents %>
    <div class="action-button" style="margin-right:.25em;">
      <%= link_to 'Create Resident', new_resident_path %>
    </div>
  <% end %>
  <div class="action-button">
    <%= link_to 'Save to File', get_csv_path %>
  </div>
</div>
<table class="residents">
  <tr>
    <th>Lot Number</th>
    <th>Name</th>
    <th>Email</th>
    <th>Address</th>
    <th>Phone</th>
    <% permitted_to? :destroy, :residents do %>
      <th class="right-align">Actions</th>
    <% end %>
  </tr>
  <%= render @residents %>
</table>

app/views/residents/new.html.erb
<h1>Create Resident</h1>

<%= form_for(@resident) do |f| %>
  <%= render 'fields', :f => f %> 
  <div class="actions">
    <%= f.submit 'Create Resident' %>
  </div>
<% end %>

app/views/residents/show.html.erb
<ul class="plain-list">
  <li>
    <% if !@resident.user.nil? %>
      <%= gravatar_for(@resident, { :size => 100 }) %>
    <% end %>
  </li>
  <li>
    <h1>
      <%= @resident.first_name + ' ' + 
        @resident.last_name %>
    </h1>
  </li>
  <% if !@resident.user.nil? %>
    <% if !@resident.user.position.nil? %>
      <li class="show-value">
        <%= 'AHOA ' + @resident.user.position.name %>
      </li>
    <% end %>
    <li class="show-value">
      <%= mail_to @resident.user.email, @resident.user.email, :encode => 'hex' %>
    </li>
  <% end %>
  <li class="show-value">
    <%= "(#{@resident.phone_area_code})
      #{@resident.phone_prefix}-#{@resident.phone_suffix}" %>
  </li>
  <li class="show-value">
    <%= @resident.residence.street_number.to_s + ' ' + @resident.residence.street_name %>
  </li>
</ul>