config/routes.rb
AmblesidecommunityOrg::Application.routes.draw do
  get "comments/destroy"

  resources :comments, only: :destroy

  resources :documents, except: :show

  resources :events

  match '/posts/:id/add_comment', to: 'posts#add_comment'
  resources :posts
  match '/blog', :to => 'posts#index'
  match '/positions/ahoa', :controller => 'positions',
    :action => 'ahoa', :as => :ahoa
  resources :positions, :except => :show

  match '/residents/get_csv', :controller => 'residents',
    :action => 'get_csv', :as => :get_csv 
  resources :residents

  match '/users/:id/verify_email/:code', :to => 'users#verify_email',
    :as => :verify_email
  match '/users/:id/toggle_active', :to => 'users#toggle_active', 
    :as => :toggle_active
  match '/users/:id/edit_roles', :to => 'users#edit_roles',
    :as => :edit_roles
  match '/users/:id/update_roles', :to => 'users#update_roles'
  match 'positions/:id/edit_assignment', :to => 'positions#edit_assignment',
    :as => :edit_assignment
  match 'positions/:id/update_assignment', :to => 'positions#update_assignment'
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :password_resets

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/community', :to => 'pages#community'
  match '/dues', :to => 'pages#dues'
  
  root :to => 'pages#home'

end

app/views/layouts/_copyright.html.erb
<div id="copyright">
  Copyright © <%= DateTime.current.year -%> Ambleside -
  <%= mail_to 'ambleside.webmaster@gmail.com', 'Contact Webmaster',
    :encode => 'hex', :subject => 'amblesidecommunity.org website' %>
</div>

app/views/layouts/_js.html.erb
<% if inject_analytics? %>
  <script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-30242717-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
  </script>
<% end %>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag :application %>
<%= stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
    <%= javascript_include_tag :application %>
  </head>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, :class => "flash #{key}") %>
  <% end %>
  <body>
    <header class="clearfix">
      <div id="banner">
        <%= link_to logo, root_path, :id => 'logo' %>  
      </div>
      <%= render 'shared/navigation' %>      
    </header>
    <div class="base-container-wrapper">
      <%= if content_for?(:subnav) 
        yield(:subnav) 
      end %>
      <div class="base-container">
        <%= content_for?(:container) ? yield(:container) : yield %>
        <%= debug(params) if Rails.env.development? %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/community.html.erb
<% content_for :subnav do %>
<div class="subnav">
  <ul class="clearfix">
    <li>
      <h3><%= link_to 'Community', community_path,
        :class => selected == 'Community' ? "selected" : "" %></h3>
    </li>
    <li>
      <h3><%= link_to 'Residents', residents_path, 
        :class => selected == 'Residents' ? "selected" : "" %></h3>
    </li>
    <li>
      <h3><%= link_to 'Blog', posts_path,
        :class => selected == 'Blog' ? "selected" : "" %></h3>
    </li>
    <li>
      <h3><%= link_to 'Events', events_path,
        :class => selected == 'Events' ? "selected" : ""  %></h3>
    </li>
    <li>
      <h3><%= link_to 'Documents', documents_path,
        :class => selected == 'Documents' ? "selected" : ""  %></h3>
    </li>
    <li>
      <h3><%= link_to 'Dues', dues_path,
        :class => selected == 'Dues' ? "selected" : ""  %></h3>
    </li>
  </ul>
</div>
<% end %>
<%= render :template => 'layouts/application' %>

app/views/layouts/pages.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= yield :meta %>
    <%= csrf_meta_tag %>
    <%= render 'shared/stylesheets' %>
    <%= stylesheet_link_tag 'pages' %>
    <%= render 'layouts/js' %>
  </head>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, :class => "flash #{key}") %>
  <% end %>
  <body>
    <div id="preloaded-images">
      <img src="//lh5.googleusercontent.com/-wpBsz8K5vgo/T6XA3h7Bg7I/AAAAAAAAABY/9iWZ3gZAL0k/s1000/isabella_green.png" />
      <img src="//lh5.googleusercontent.com/-NhCyDNcYPO0/T6XA23EwV2I/AAAAAAAAABM/bOYniIeSU_Y/s960/east_gate.png" />
      <img src="//lh4.googleusercontent.com/-8vXKi02WIvU/T6XA16Y30eI/AAAAAAAAAA4/9bhDpE0neYQ/s960/ducks.png" />
      <img src="//lh4.googleusercontent.com/-oBTFHfZJfkQ/T6iUPICzYdI/AAAAAAAAAB0/BzS8eNtD4Kg/s800/waterfall.png" />
    </div>
    <div id="backgrounds"></div>
    <header>
      <div id="browser-warning">
        <p>
          It appears that you have a really old browser that will not render this site correctly.  Please consider upgrading to a standards compliant browser in order to have full functionality.
        </p>
        <p>
          I recommend Google Chrome or Firefox.  Here is a site that will help you pick the latest version: <a href="http://www.browsehappy.com" target="_blank" alt="Browse Happy">BrowseHappy.com</a>
        </p>
      </div>
      <div id="nav-bar">
        <%= link_to logo, root_path, :id => 'logo' %>
        <%= render 'shared/navigation' %>
        <div style="clear:both;"></div>
      </div>
    </header>
    <section>
      <div id="images-loading">
        <img height="64" width="64" src=<%= asset_path 'spinner.gif' %> />
      </div>
      <%= content_for?(:body) ? yield(:body) : nil %>
    </section>
    <footer>
      <%= yield :footer %>
    </footer>
    <%= javascript_include_tag :application %>
  </body>
</html>

app/views/layouts/pages_minimal.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sign In</title>
    <%= csrf_meta_tag %>
    <%= render 'layouts/stylesheets' %>
    <%= stylesheet_link_tag 'pages_minimal' %>
  </head>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, :class => "flash #{key}") %>
  <% end %>
  <div id="preloaded-images">
    <img src="//lh5.googleusercontent.com/-wpBsz8K5vgo/T6XA3h7Bg7I/AAAAAAAAABY/9iWZ3gZAL0k/s1000/isabella_green.png" />
    <img src="//lh5.googleusercontent.com/-NhCyDNcYPO0/T6XA23EwV2I/AAAAAAAAABM/bOYniIeSU_Y/s960/east_gate.png" />
    <img src="//lh4.googleusercontent.com/-8vXKi02WIvU/T6XA16Y30eI/AAAAAAAAAA4/9bhDpE0neYQ/s960/ducks.png" />
  </div>
  <body>
    <div id="backgrounds"></div>
    <div id="browser-warning">
      <p>
        It appears that you have a really old browser that will not render this site correctly.  Please consider upgrading to a standards compliant browser in order to have full functionality.
      </p>
      <p>
        I recommend Google Chrome or Firefox.  Here is a site that will help you pick the latest version: <a href="http://www.browsehappy.com" target="_blank" alt="Browse Happy">BrowseHappy.com</a>
      </p>
    </div>
    <div id="images-loading">
      <img height="64" width="64" src=<%= asset_path 'spinner.gif' %> />
    </div>
    <%= content_for?(:body) ? yield(:body) : nil %>
  </body>
  <%= javascript_include_tag :application %>
  <%= render 'layouts/js' %>
</html>